### ISSUE TITLE
Mod Version 1.20.1 doesn't work

### ISSUE THREAD

**Issue by Umbra09** [TheWitherlord/GeoSmelt#1]
Hello, as you will see below, I only have this mod in one of my profiles and in v.1.20.1 the mod doesn't work. But in v.1.20.4 I could see that, when I downloaded it to a new profile, the profile downloaded upodates and patches (5 steps) and not in the profile that has this version (1.20.1). In the case of the later version the mod only downloads itself in the profile.
![imagen_2024-06-03_121807223](https://github.com/TheWitherlord/GeoSmelt/assets/171612942/93995f1a-8051-4c5a-ad01-dc0df5586668)
![imagen_2024-06-03_121905096](https://github.com/TheWitherlord/GeoSmelt/assets/171612942/2732954e-810e-4655-a673-63a1a275f73d)
![imagen_2024-06-03_121918054](https://github.com/TheWitherlord/GeoSmelt/assets/171612942/025eac88-b473-4829-8633-c6f3cb224878)
I really don't know what is happening.

**Comment by TheWitherlord** [comment]
Hello, thanks for the issue.

Looks like you don't have farmer's delight installed, its a dependency because the mod adds knives for it.

If this isn't the case just simply post your latest log or a crash report here.
You can use gist: https://gist.github.com/

Thank you!

**Comment by Umbra09** [comment]
But if that was the case, why did it worked when I made another profile to see what the mod had for version 1.20.4 and I didn't had Farmer's delight installled? The only difference was that, when I installed v 1.20.4 (or .6) in the profile, it said: Updating and Patching steps 1 out of 5 or 6, something like that...

Edit: IT WORKED :'V TYVM, I can finally enjoy your awesome mod! Have a good Day :D

**Comment by Umbra09** [comment]
This Issue is now Resolved

**Comment by TheWitherlord** [comment]
> But if that was the case, why did it worked when I made another profile to see what the mod had for version 1.20.4 and I didn't had Farmer's delight installled? The only difference was that, when I installed v 1.20.4 (or .6) in the profile, it said: Updating and Patching steps 1 out of 5 or 6, something like that...
> 
> Edit: IT WORKED :'V TYVM, I can finally enjoy your awesome mod! Have a good Day :D

Oh, its because the 1.20.4 version removed knives. If I ever update past 1.20.4 the knives and stuff will be moved to a new mod.
