### ISSUE TITLE
[1.21.1 Neoforge] 'Failed to create mob' log spam

### ISSUE THREAD

**Issue by Darkfiend009** [TheWitherlord/GeoSmelt#2]
I've updated my modpack and added it to a server yesterday. I noticed a lot of log spam/warns in the console showing "Failed to create mob) for the Skeleton Warrior.

I was connected for about 2 minutes and this was the debug.log output.

debug.log: https://gist.github.com/Darkfiend009/1084ec9ac2f8e57f5db81657da65c6aa

Minecraft: 1.21.1
Neoforge: 21.1.42
GeoSmelt: 3.1.1

**Comment by TheWitherlord** [comment]
Oh hi

Can you test if this was fixed in the latest version. You are using 3.1.1. and this was fixed in 3.1.2

Glad you are using the issue tracker :)

**Comment by TheWitherlord** [comment]
should be fixed

**Comment by Darkfiend009** [comment]
Sorry for the delayed response. IRL got in the way. It was indeed fixed!
